### ISSUE TITLE
Price on application product

### ISSUE THREAD

**Issue by philcon93** [robm2002/Wholesale-Deluxe#2]
This product thumbnail has a 'price on application' button not allowing users to buy it. But on the product page it has an add to cart button, is this meant to be like this?
- http://wholesaledeluxetheme.neto.com.au/breville-bes870bss-the-barista-express

![screen shot 2016-07-15 at 3 57 50 pm](https://cloud.githubusercontent.com/assets/13529653/16865023/1608231e-4aa5-11e6-95da-42949d701873.png)

---

![screen shot 2016-07-15 at 3 59 07 pm](https://cloud.githubusercontent.com/assets/13529653/16865024/160822ba-4aa5-11e6-96f4-9d928ee137cd.png)

**Comment by robm2002** [comment]
This was fixed a while back
