### ISSUE TITLE
Add to cart thumbnail

### ISSUE THREAD

**Issue by craigblunden** [robm2002/Wholesale-Deluxe#3]
Not sure if tweaks were involved with this.

![screen shot 2016-09-19 at 11 58 38 am](https://cloud.githubusercontent.com/assets/11847839/18621014/779da45c-7e60-11e6-99eb-c2fbba4bdac1.png)

**Example**
http://wholesale.wfplastic.com.au/?nview=wholesaledeluxe

**Comment by robm2002** [comment]
Tweakypoo
