### ISSUE TITLE
Header checkout links don't work

### ISSUE THREAD

**Issue by quatlin** [robm2002/Wholesale-Deluxe#5]
https://github.com/robm2002/Wholesale-Deluxe/blob/master/src/templates/headers/template.html#L167 should be `[%url page:'checkout' type:'payment'/%]`

https://github.com/robm2002/Wholesale-Deluxe/blob/master/src/templates/headers/template.html#L165 should be `[%url page:'checkout' fn:'quote'/%]

They also appear to be missing closing `li` tags

**Comment by robm2002** [comment]
Fixed
